apiVersion: v1
kind: Service
metadata:
  name: country-service
  namespace: jenkins
spec:
  selector:
    app: country-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 31442
